### ISSUE TITLE
Hi there, your Maven elasticemail dependencies doesn't exist in the maven repo. 

### ISSUE THREAD

**Issue by RaphaelChia** [ElasticEmail/elasticemail-java#1]
`<dependency>
			<groupId>com.elasticemail</groupId>
			<artifactId>elasticemail</artifactId>
			<version>4.0.13</version>
		</dependency>`

this above code leads to an error. Is there another way to use elasticemail with maven?

**Comment by radzaw** [comment]
Hi,

You have to include repository and github credentials - for example:

- in your pom.xml

```
    <repositories>
        <repository>
            <id>github</id>
            <name>GitHub ElasticEmail Apache Maven Packages</name>
            <url>https://maven.pkg.github.com/ElasticEmail/elasticemail-java</url>
            <releases><enabled>true</enabled></releases>
            <snapshots><enabled>true</enabled></snapshots>
        </repository>
    </repositories>

    <dependencies>
        <dependency>
            <groupId>com.elasticemail</groupId>
            <artifactId>elasticemail</artifactId>
            <version>4.0.13</version>
        </dependency>
    </dependencies>
```

- in your settings.xml

```
<settings>
  <servers>
    <server>
      <id>github</id>
      <username>mygithubusername</username>
      <password>mygithubpersonalaccesstoken</password>
    </server>
  </servers>
</settings>
```

**Comment by RaphaelChia** [comment]
Alright, thank you!

**Comment by doggie1989** [comment]
For Gradle project,

add these in build.gradle
``
repositories {
	mavenCentral()
	maven { url "https://maven.pkg.github.com/ElasticEmail/elasticemail-java" }
}

implementation 'com.elasticemail:elasticemail:4.0.16'
``

**Comment by constantine-d** [comment]
Hello i get 401 while trying to get the dependency.
I have this in my pom:
```
<repositories>
    <repository>
        <id>github</id>
        <name>GitHub ElasticEmail Apache Maven Packages</name>
        <url>https://maven.pkg.github.com/ElasticEmail/elasticemail-java</url>
        <releases><enabled>true</enabled></releases>
        <snapshots><enabled>true</enabled></snapshots>
    </repository>
</repositories>
<dependency>
    <groupId>com.elasticemail</groupId>
    <artifactId>elasticemail</artifactId>
    <version>4.0.16</version>
    <scope>compile</scope>
</dependency>
```
I also have settings.xml in my .m2 folder with
```
<settings>
  <servers>
    <server>
      <id>github</id>
      <username>mygithubusername</username>
      <password>mygithubpersonalaccesstoken</password>
    </server>
  </servers>
</settings>
```

Please help

**Comment by constantine-d** [comment]
Hi again, I gave up on that. I chose another way around. It is also mentioned in the instructions. Here is what you do if you face problems like mine:

1. clone the repo
2. `mvn clean package`. You might have to skip the test compilation. It gave some errors when i tried it the first time. You will get some jar files.
3. then install the jar into you local repository: ```mvn install:install-file -Dfile=elasticemail-4.0.16.jar -DgroupId=local -DartifactId=elasticemail -Dversion=4.0.16 -Dpackaging=jar```. 
4. then you can use the dependency in your pom file. Like this:
```
<dependency>
    <groupId>local</groupId>
    <artifactId>elasticemail</artifactId>
    <version>4.0.16</version>
</dependency>
```
